apiVersion: ingress.github.com/v1beta1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app-sample
    app.kubernetes.io/part-of: demo4kubebuilder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: demo4kubebuilder
  name: app-sample
spec:
  image: nginx:latest
  replicas: 2
  enable_ingress: true
  enable_service: true
